### PR TITLE
Make project buildable and testable with Bazel.

### PR DESCRIPTION
**Pull request by DrMarcII**
- Use bazel to run tests in travis build.

### CODE REVIEW

**Comment by DrMarcII** [comment]
This is not ready for submit.

**Comment by DrMarcII** [comment]
Also this change depends on https://github.com/dart-lang/rules_dart/pull/61 to work correctly.

**Comment by DrMarcII** [comment]
@nshahan PTAL

**Comment by DrMarcII** [comment]
The test failure seems to be some inherent flakiness somewhere in this project. Not sure where, but will try to trace it down.

**Comment by nshahan** [comment]
LGTM

**Comment by nshahan** [comment]
Linking to discussion had elsewhere about checking in these BUILD files as a reference. 
https://github.com/dart-lang/rules_dart/pull/61

**Pull request merged**
