### PR TITLE
Add in-browser/webdriver hybrid test runner

### PR DESCRIPTION
**Pull request by DrMarcII**

### CODE REVIEW

**Comment by DrMarcII** [comment]
@kevmoo @nex3

FYI: This pull request implements hybrid testing: tests that are run in a browser started via webdriver and have access to the webdriver that started them. They are useful because in-browser tests are great until you need to start working with input (mouse/keyboard) events, at which point webdriver has the advantage.

The main takeaway here is that this provides an example of the sort of extension/customization that at least one user (me) would like to see supported in test:
 - add new handlers to the web server used for browser-based testing (used to expose a webdriver api to the test that can be called via xhr)
 - swap out the browser launching implementation (switch to webdriver for launching browser rather than calling executables directly)

Currently to do this, I had to copy src/executable.dart (changed to use my version of src/runner/loader.dart), src/runner/loader.dart (changes to use my version of server.dart), and src/runner/browser/server.dart (added new handler and switched the browser launching implementation).

**Comment by nex3** [comment]
Thanks for looking into this! It's really valuable to know what extension points people need.

> add new handlers to the web server used for browser-based testing (used to expose a webdriver api to the test that can be called via xhr)

This isn't a use-case we'd considered; I've filed dart-lang/test#109 to track it.

> swap out the browser launching implementation (switch to webdriver for launching browser rather than calling executables directly)

We've already got dart-lang/test#99 tracking this :smiley_cat:.

> Currently to do this, I had to copy src/executable.dart (changed to use my version of src/runner/loader.dart), src/runner/loader.dart (changes to use my version of server.dart), and src/runner/browser/server.dart (added new handler and switched the browser launching implementation).

This is fine for pre-release stuff, but are you planning on releasing a stable version of this code before the test infrastructure is in place to support it?

**Comment by DrMarcII** [comment]
Thanks for the feedback @nex3

> Currently to do this, I had to copy src/executable.dart (changed to use my
> version of src/runner/loader.dart), src/runner/loader.dart (changes to use
> my version of server.dart), and src/runner/browser/server.dart (added new
> handler and switched the browser launching implementation).
>
> This is fine for pre-release stuff, but are you planning on releasing a
> stable version of this code before the test infrastructure is in place to
> support it?
>
Not really. Mostly I wanted to provide a concrete example of the sort of
extension that I am considering to help guide the development of the test
package :-)

**Comment by nex3** [comment]
> Not really. Mostly I wanted to provide a concrete example of the sort of
extension that I am considering to help guide the development of the test
package :-)

Awesome, much appreciated.

**Pull request closed without merging**
