### PR TITLE
Fixes for window_test

### PR DESCRIPTION
**Pull request by DrMarcII**
Should fix Issues #18 and #31.

### CODE REVIEW

**Comment by DrMarcII** [comment]
@devoncarew are you able to try this and can you see if it fixes issue #31 (I don't have a Mac to run this on)?

**Comment by devoncarew** [comment]
Here are the results. I had some trouble getting your DrMarcII:master branch; I ended up manually patching this into my copy.

```
PASS: Alert no alert

PASS: Alert text

PASS: Alert accept

PASS: Alert dismiss

PASS: Alert sendKeys

PASS: Keyboard sendKeys -- once

PASS: Keyboard sendKeys -- twice

PASS: Keyboard sendKeys -- with tab

PASS: Mouse moveTo element/click

PASS: Mouse moveTo coordinates/click

PASS: Mouse moveTo element coordinates/click

PASS: Mouse down/up

PASS: Mouse doubleClick

PASS: Navigation forward/back

ERROR: Navigation refresh
  Test failed: Caught Expected SERE
  test/src/navigation_test.dart 31:9  main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                        _RawReceivePortImpl._handleMessage
  

ERROR: Cookies add simple cookie
  Test failed: Caught Class '_ControllerStream' has no instance getter 'iterator'.
  
  NoSuchMethodError: method not found: 'iterator'
  Receiver: Instance of '_ControllerStream'
  Arguments: []
  dart:core                         Object.noSuchMethod
  test/src/options_test.dart 22:26  main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                      _RawReceivePortImpl._handleMessage
  

ERROR: Cookies add complex cookie
  Test failed: Caught Class '_ControllerStream' has no instance getter 'iterator'.
  
  NoSuchMethodError: method not found: 'iterator'
  Receiver: Instance of '_ControllerStream'
  Arguments: []
  dart:core                         Object.noSuchMethod
  test/src/options_test.dart 37:26  main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                      _RawReceivePortImpl._handleMessage
  

ERROR: Cookies delete cookie
  Test failed: Caught Class '_ControllerStream' has no instance getter 'iterator'.
  
  NoSuchMethodError: method not found: 'iterator'
  Receiver: Instance of '_ControllerStream'
  Arguments: []
  dart:core                         Object.noSuchMethod
  test/src/options_test.dart 52:26  main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                      _RawReceivePortImpl._handleMessage
  

PASS: Cookies delete all cookies

PASS: TimeOuts set all timeouts

PASS: TargetLocator frame index

PASS: TargetLocator frame name

PASS: TargetLocator frame element

PASS: TargetLocator root frame

PASS: WebDriver create default

PASS: WebDriver create chrome

PASS: WebDriver create firefox

PASS: WebDriver methods get

PASS: WebDriver methods currentUrl

PASS: WebDriver methods findElement -- success

PASS: WebDriver methods findElement -- failure

PASS: WebDriver methods findElements -- 1 found

PASS: WebDriver methods findElements -- 4 found

PASS: WebDriver methods findElements -- 0 found

PASS: WebDriver methods pageSource

PASS: WebDriver methods close/windows

ERROR: WebDriver methods window
  Test failed: Caught Class '_ControllerStream' has no instance getter 'iterator'.
  
  NoSuchMethodError: method not found: 'iterator'
  Receiver: Instance of '_ControllerStream'
  Arguments: []
  dart:core                             Object.noSuchMethod
  test/src/web_driver_test.dart 114:31  main.<fn>.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                          _RawReceivePortImpl._handleMessage
  

PASS: WebDriver methods activeElement

PASS: WebDriver methods windows

PASS: WebDriver methods execute

PASS: WebDriver methods executeAsync

PASS: WebDriver methods captureScreenshot

PASS: WebElement click

PASS: WebElement submit

PASS: WebElement sendKeys

PASS: WebElement clear

PASS: WebElement enabled

PASS: WebElement displayed

PASS: WebElement location -- table

PASS: WebElement location -- invisible

PASS: WebElement size -- table

PASS: WebElement size -- invisible

PASS: WebElement name

PASS: WebElement text

PASS: WebElement findElement -- success

PASS: WebElement findElement -- failure

PASS: WebElement findElements -- 1 found

PASS: WebElement findElements -- 4 found

PASS: WebElement findElements -- 0 found

PASS: WebElement attributes

PASS: WebElement cssProperties

PASS: WebElement equals

PASS: Window size

PASS: Window location

FAIL: Window maximize
  Expected: a value less than <100>
    Actual: <100>
     Which: is not a value less than <100>
  
  package:unittest/src/simple_configuration.dart 15:28  _ExpectFailureHandler.fail
  package:matcher/src/expect.dart 121:9                 DefaultFailureHandler.failMatch
  package:matcher/src/expect.dart 95:29                 expect
  test/src/window_test.dart 38:13                       main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                                          _RawReceivePortImpl._handleMessage
  


59 PASSED, 1 FAILED, 5 ERRORS
```

**Comment by DrMarcII** [comment]
```
ERROR: Navigation refresh
  Test failed: Caught Expected SERE
  test/src/navigation_test.dart 31:9  main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                        _RawReceivePortImpl._handleMessage
```
This failure surprises me. Maybe I need to change this to a wait.

```
ERROR: Cookies add simple cookie
  Test failed: Caught Class '_ControllerStream' has no instance getter 'iterator'.

  NoSuchMethodError: method not found: 'iterator'
  Receiver: Instance of '_ControllerStream'
  Arguments: []
  dart:core                         Object.noSuchMethod
  test/src/options_test.dart 22:26  main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                      _RawReceivePortImpl._handleMessage


ERROR: Cookies add complex cookie
  Test failed: Caught Class '_ControllerStream' has no instance getter 'iterator'.

  NoSuchMethodError: method not found: 'iterator'
  Receiver: Instance of '_ControllerStream'
  Arguments: []
  dart:core                         Object.noSuchMethod
  test/src/options_test.dart 37:26  main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                      _RawReceivePortImpl._handleMessage


ERROR: Cookies delete cookie
  Test failed: Caught Class '_ControllerStream' has no instance getter 'iterator'.

  NoSuchMethodError: method not found: 'iterator'
  Receiver: Instance of '_ControllerStream'
  Arguments: []
  dart:core                         Object.noSuchMethod
  test/src/options_test.dart 52:26  main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                      _RawReceivePortImpl._handleMessage
```
These are occurring in places where I am using await for, so I am guessing your version of Dart doesn't support it (I am not sure which version added it). You could change 
```
await for (var x in y) {
}
```
into
```
for (var x in await y.toList()) {
}
```
to get this working.
```
FAIL: Window maximize
  Expected: a value less than <100>
    Actual: <100>
     Which: is not a value less than <100>

  package:unittest/src/simple_configuration.dart 15:28  _ExpectFailureHandler.fail
  package:matcher/src/expect.dart 121:9                 DefaultFailureHandler.failMatch
  package:matcher/src/expect.dart 95:29                 expect
  test/src/window_test.dart 38:13                       main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                                          _RawReceivePortImpl._handleMessage
```
Suspect that this is back to Mac OS X maximize being weird (doesn't have a real maximize).

**Comment by DrMarcII** [comment]
I was wrong on the await for. I had run the files through dartformat before adding to pull request, and it apparently strips await from await for (will file a bug).

**Comment by devoncarew** [comment]
Interesting. Likely a bug in the analyzer library; Bob will be able to tell
and route the issue.

On Fri, Jan 30, 2015 at 10:22 AM, Marc Fisher <notifications@github.com>
wrote:

> I was wrong on the await for. I had run the files through dartformat
> before adding to pull request, and it apparently strips await from await
> for (will file a bug).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/webdriver.dart/pull/34#issuecomment-72245922>.
>



-- 
Devon Carew
Software Engineer
Google, Inc.

**Pull request merged**
