### PR TITLE
get tests running on the bot using chromedriver

### PR DESCRIPTION
**Pull request by devoncarew**
- set up a xvfb on travis
- have a common `createTestDriver()` method
- install `chromedriver` on travis
- set up args to start chromium instead of chrome (`/usr/bin/chromium-browser`) - travis comes with chromium available. Also, start chromium with the `--no-sandbox` cli arg - otherwise chrome won't start up under travis' virtualization

This PR may take a few rounds to get working -

### CODE REVIEW

**Comment by devoncarew** [comment]
> E: Unable to locate package chromium-chromedriver

**Comment by devoncarew** [comment]
> Setup failed: Caught UnknownException (13): unknown error: Chrome version must be >= 39.0.2171.0
    (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Linux 2.6.32-042stab090.5 x86_64)

Looks like the version of chromedriver we installed is too new to drive the version of chromium that travis comes with.

**Comment by devoncarew** [comment]
Pretty close:

```
ERROR: Navigation refresh
  Test failed: Caught Expected SERE
  test/src/navigation_test.dart 32:9  main.<fn>.<fn>.<<fn>_async_body>
  dart:isolate                        _RawReceivePortImpl._handleMessage
```

**Comment by DrMarcII** [comment]
I suspect that it will pass when you merge in the most recent changes.

Thanks for working on this.

**Comment by devoncarew** [comment]
> Thanks for working on this.

Absolutely! I'm hoping to use this to test my current project (dartpad), and to improve options for dart ui testing in general.

**Pull request closed without merging**
