### PR TITLE
Make stuff strong-mode happy

### PR DESCRIPTION
**Pull request by srawlins**
This is mostly just casting function return values, as they are JSON-esque, or just kind of overloaded.

### CODE REVIEW

**Comment by srawlins** [comment]
Ping @DrMarcII can merge #121 first and then I can resolve; its mostly a superset of #121.

**Comment by goderbauer** [comment]
Can you rebase this on top of the current master?

**Comment by srawlins** [comment]
Rebased.

**Comment by goderbauer** [comment]
LGTM.

**Pull request merged**
