### PR TITLE
Fix formatting and analysis issues

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Comment by hernandezmshawntae** [comment]
Please and Thank You.

**Comment by hernandezmshawntae** [comment]
Please and Thank You.

**Comment by hernandezmshawntae** [comment]
Please and Thank You.

**Comment by hernandezmshawntae** [comment]
privacy issues sata loss please and thank you  incorrect license

**Comment by hernandezmshawntae** [comment]
privacy issues please and thank you

**Pull request merged**
